### ISSUE TITLE
docs오타및 일반전 업데이트 불가

### ISSUE THREAD

**Issue by popop098** [gunyu1019/PUBG-API#2]
**오타**
![이미지](https://media.discordapp.net/attachments/774801225807429642/799629934183448606/unknown.png)

normal인데 ranked로 적혀있음

**에러**
```https://yhs.kr/api/PUBG/normal/update/?id=ID```
로 GET요청하였으나 에러가 발생하여 업데이트가 불가능함
랭크전은 정상적으로 업데이트됨

![이미지](https://media.discordapp.net/attachments/757227192806539385/799631871943770122/unknown.png)

**Comment by gunyu1019** [comment]
```pytb
Traceback (most recent call last):
  File "/home/{SERVER_NAME}/.local/lib/python3.7/site-packages/sanic/app.py", line 939, in handle_request
    response = await response
  File "PUBG_API_sanic/main.py", line 233, in update_normal_status
    await s_info.normal_status_update(pubg_id, platform_info, season)
AttributeError: module 'status' has no attribute 'normal_status_update'
```
 버그가 확인되었으며, 현 마감 일정 지연으로 인하여 처리가 늦어질 수 있으니, 양해부탁드립니다.

**Comment by popop098** [comment]
언제 처리되려나요..?

**Comment by gunyu1019** [comment]
[Fixed](https://github.com/gunyu1019/PUBG-API/commit/d26c4ebc054750cb2a28eba8feff00674e34f263)
